### PR TITLE
Additional rules for luci statistics and some others

### PR DESCRIPTION
**Pull request by tobiaswaldvogel**
These are some additional rules for luci statistics and some missing allows to /dev/urandom
Luci-statistics requires access to the statistics files in /tmp/rrd and the definitions in /usr/share/luci/statistics.
I created an addtional file for labeling /tmp/rrd as these files are not only used by luci but also by collectd which is updating them. Collect itself is probably also difficult to target as it has many plugins, but for now I think it is good enough to it in sys.subj

### CODE REVIEW

**Comment by doverride** [comment]
The thing is that if you tie /tmp/rrd to collectd and associate that with a collectd specific type then anything else also using rrd and using that location would need to have access to that collectd.tmpfile type content. That is not a problem per se but it implies that /tmp/rrrd is something collectd specific, which it is not. Instead its rrd specific and just used by various programs.

**Comment by doverride** [comment]
tying /tmp/rrd to collectd would effectively either add a dependency for colllectd on any other program using rrd and /tmp/rrd or would introduce a conflict with duplicate different specifications for /tmp/rrd.

This is why /tmp/rrd should be labeled rrd.tmpfile in src/agent/rrd.cil. Ideally programs using rrd should tell rrd to use a private rrd tmpfile location (for example /tmp/collectd/rrd but that is watter under the bridge.

**Comment by tobiaswaldvogel** [comment]
Thanks a lot for you guidance. I totally agree that this would be the best way and reworked it the way you said. It also makes maintenance much simpler. I'm preparing a new pull request with this.

Just one final question: So the rrd files in the use case of luci-statistics are written by collectd to /tmp/rrd and then rendered with rddtool. For every diagram I get then a

`avc:  granted  { execute_no_trans } for  pid=27484 comm="cgi-exec" path="/usr/bin/rrdtool" dev="overlay" ino=1132 scontext=u:r:cgiio.subj tcontext=u:r:file.execfile tclass=file`

which is triggered by

```
src/file/execfile.cil
     (macro auditallow_execute_execfile_files ((type ARG1))
           (auditallow ARG1 execfile (file (execute_no_trans))))
```

I would prefer to suppress these audit messages in this context in order not to spam the kernel log. What do you think would be the best way to do so?

**Comment by doverride** [comment]
Yes eventually that rule should be removed but i added it for exactly this purpose. We should target /usr/sbin/rrdtool. Only shell utils should have type exec.execfile generally at least.

**Comment by doverride** [comment]
So yes eventually policy for rrdtool should be added also to src/agent/rrd.cil
```
(block rrd

          ....

         (block rrdtool

                   ....))

(in .cgiio

     (call .rrd.rrdtool.subj_type_transition (subj)))
```

**Comment by tobiaswaldvogel** [comment]
Thanks, that was exactly what I was looking for. I'll close this pull request then and create a new one

**Pull request closed without merging**
